### ISSUE TITLE
Issue: Padder in native-resolution plugin needs TypeError handling for non-callable object

### ISSUE THREAD

**Issue by Sante96** [Jaded-Encoding-Thaumaturgy/vs-preview-plugins#15]
### Current Behavior
 The native-resolution plugin currently tries to use `padder` as a callable function, which results in a TypeError: 

``` self.padded_clip_cache[clip] = padder( clip.std.Crop(side_cut, side_cut, top_cut, top_cut), side_cut // 2, side_cut // 2, top_cut, top_cut ).std.Transpose() ```

 Error: `TypeError: '_padder' object is not callable`

 ### Fix Applied 

Modified the code to use the correct `MIRROR` method from padder: 

``` self.padded_clip_cache[clip] = padder.MIRROR( clip.std.Crop(side_cut, side_cut, top_cut, top_cut), side_cut // 2, side_cut // 2, top_cut, top_cut ).std.Transpose() ```

 ### Context 

This issue was found in the native-resolution plugin's DCT analysis function where padding is used to handle edge cases. MIRROR padding was chosen as it's the most appropriate method for analyzing native resolution as it creates fewer artifacts at the edges that could affect the DCT analysis. 

### Additional Information

 The fix maintains the same functionality while using the correct API - MIRROR padding is particularly suitable for DCT analysis as it preserves edge continuity - This change improves code stability without affecting the plugin's analysis results

[https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview-plugins/blob/master/native-res/native_resolution.ppy#L358](url)

**Comment by LightArrowsEXE** [comment]
https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview-plugins/blob/master/native-res/native_resolution.ppy#L358

This is already implemented.
