### ISSUE TITLE
Remove "Width & Height" check from native-res

### ISSUE THREAD

**Issue by wiwaz** [Jaded-Encoding-Thaumaturgy/vs-preview-plugins#6]
As we already know, image resampling (for non-EWA kernels) is a separable process. We can use this to our advantage by only checking one dimension at a time. By only checking one dimension we can have more accurate results and prevent failures if only one dimension has been rendered unrecoverable. Checking both dimensions at once would only prove useful for EWA kernels, but the descale plugin does not support EWA descales anyway. The feature may aswell be removed as with our current landscape its not only not useful, but rather actively misleading.

**Comment by LightArrowsEXE** [comment]
I agree, but I think it's best to leave the code for that in tact so that in the event we ever add EWA support (and, more vitally, we find EWA kernels actually being used in productions), we can add the feature back very trivially.

**Comment by wiwaz** [comment]
At the very least it should not be available as an option when checking the error of a non-EWA kernel (which is all of them atm)
